namespace Icod.ProcPs.Shared;

using System.Globalization;

public enum ProcFieldKind { Pid, ParentPid, ProcessGroup, Session, Command, CommandLine, State, EffectiveUser, Terminal, Nice, Threads, ResidentMemory, VirtualMemory }
public enum ProcFieldAlignment { Left, Right }
public sealed class ProcFieldDefinition { public ProcFieldKind Kind{get;} public string Name{get;} public string Header{get;} public int MinimumWidth{get;} public ProcFieldAlignment Alignment{get;} public ProcFieldDefinition(ProcFieldKind kind,string name,string header,int minimumWidth,ProcFieldAlignment alignment){ArgumentException.ThrowIfNullOrWhiteSpace(name);ArgumentNullException.ThrowIfNull(header);ArgumentOutOfRangeException.ThrowIfNegative(minimumWidth);this.Kind=kind;this.Name=name;this.Header=header;this.MinimumWidth=minimumWidth;this.Alignment=alignment;} }
public static class ProcFieldCatalog {
	private static readonly IReadOnlyList<ProcFieldDefinition> DefinitionsValue = new[]{new ProcFieldDefinition(ProcFieldKind.Pid,"pid","PID",5,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.ParentPid,"ppid","PPID",5,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.ProcessGroup,"pgid","PGID",5,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.Session,"sid","SID",5,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.EffectiveUser,"euid","EUID",5,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.Terminal,"tty","TTY",8,ProcFieldAlignment.Left),new ProcFieldDefinition(ProcFieldKind.State,"state","S",1,ProcFieldAlignment.Left),new ProcFieldDefinition(ProcFieldKind.Nice,"ni","NI",3,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.Threads,"nlwp","NLWP",4,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.ResidentMemory,"rss","RSS",6,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.VirtualMemory,"vsz","VSZ",7,ProcFieldAlignment.Right),new ProcFieldDefinition(ProcFieldKind.Command,"comm","COMMAND",15,ProcFieldAlignment.Left),new ProcFieldDefinition(ProcFieldKind.CommandLine,"args","COMMAND",20,ProcFieldAlignment.Left)};
	public static IReadOnlyList<ProcFieldDefinition> Definitions=>DefinitionsValue; public static ProcFieldDefinition? Find(string name){ArgumentException.ThrowIfNullOrWhiteSpace(name);return DefinitionsValue.FirstOrDefault(field=>string.Equals(field.Name,name,StringComparison.OrdinalIgnoreCase));}
	public static string Format(ProcProcessSnapshot process,ProcFieldKind kind){ArgumentNullException.ThrowIfNull(process);return kind switch{ProcFieldKind.Pid=>process.ProcessId.ToString(CultureInfo.InvariantCulture),ProcFieldKind.ParentPid=>FormatObserved(process.ParentProcessId),ProcFieldKind.ProcessGroup=>FormatObserved(process.ProcessGroupId),ProcFieldKind.Session=>FormatObserved(process.SessionId),ProcFieldKind.Command=>process.CommandName.HasValue?process.CommandName.Value:"-",ProcFieldKind.CommandLine=>process.CommandLineArguments.HasValue?string.Join(" ",process.CommandLineArguments.Value):"-",ProcFieldKind.State=>process.State.HasValue?StateCode(process.State.Value):"-",ProcFieldKind.EffectiveUser=>FormatObserved(process.EffectiveUserId),ProcFieldKind.Terminal=>process.Terminal.HasValue?process.Terminal.Value.Name??process.Terminal.Value.DeviceNumber.ToString(CultureInfo.InvariantCulture):"-",ProcFieldKind.Nice=>FormatObserved(process.NiceValue),ProcFieldKind.Threads=>FormatObserved(process.ThreadCount),ProcFieldKind.ResidentMemory=>FormatObserved(process.ResidentMemoryBytes),ProcFieldKind.VirtualMemory=>FormatObserved(process.VirtualMemoryBytes),_=>throw new ArgumentOutOfRangeException(nameof(kind))};}
	private static string FormatObserved<T>(ProcObservedValue<T> value)where T:IFormattable=>value.HasValue?value.Value.ToString(null,CultureInfo.InvariantCulture):"-"; private static string StateCode(ProcProcessState state)=>state switch{ProcProcessState.Running=>"R",ProcProcessState.Sleeping=>"S",ProcProcessState.DiskSleep=>"D",ProcProcessState.Stopped=>"T",ProcProcessState.TracingStop=>"t",ProcProcessState.Zombie=>"Z",ProcProcessState.Dead=>"X",ProcProcessState.Idle=>"I",ProcProcessState.Waking=>"W",ProcProcessState.Parked=>"P",_=>"?"};
}
public enum ProcPersonality { Linux, Posix, Bsd, SunOs4, Digital, Hp, Aix }
public static class ProcPersonalityResolver { public static bool TryParse(string? text,out ProcPersonality personality){personality=ProcPersonality.Linux;if(string.IsNullOrWhiteSpace(text))return false;switch(text.Trim().ToLowerInvariant()){case "linux":personality=ProcPersonality.Linux;return true;case "posix":case "sysv":case "unix":personality=ProcPersonality.Posix;return true;case "bsd":personality=ProcPersonality.Bsd;return true;case "sunos4":case "sun":personality=ProcPersonality.SunOs4;return true;case "digital":case "tru64":personality=ProcPersonality.Digital;return true;case "hp":case "hpux":personality=ProcPersonality.Hp;return true;case "aix":personality=ProcPersonality.Aix;return true;default:return false;}} public static ProcPersonality ResolveEnvironment(IReadOnlyDictionary<string,string?> environment){ArgumentNullException.ThrowIfNull(environment);foreach(var name in new[]{"PS_PERSONALITY","CMD_ENV"})if(environment.TryGetValue(name,out var value)&&TryParse(value,out var personality))return personality;return ProcPersonality.Linux;} }
public sealed class ProcSortKey { public ProcFieldKind Field{get;} public bool Descending{get;} public ProcSortKey(ProcFieldKind field,bool descending=false){this.Field=field;this.Descending=descending;} }
public static class ProcProcessSorter { public static IReadOnlyList<ProcProcessSnapshot> Sort(IEnumerable<ProcProcessSnapshot> processes,IEnumerable<ProcSortKey> keys){ArgumentNullException.ThrowIfNull(processes);ArgumentNullException.ThrowIfNull(keys);var keyArray=keys.ToArray();var indexed=processes.Select((process,index)=>(process,index)).ToList();indexed.Sort((left,right)=>{foreach(var key in keyArray){var comparison=CompareField(left.process,right.process,key.Field);if(0!=comparison)return key.Descending?-comparison:comparison;}return left.index.CompareTo(right.index);});return indexed.Select(item=>item.process).ToArray();} private static int CompareField(ProcProcessSnapshot left,ProcProcessSnapshot right,ProcFieldKind field)=>field switch{ProcFieldKind.Pid=>left.ProcessId.CompareTo(right.ProcessId),ProcFieldKind.ParentPid=>CompareObserved(left.ParentProcessId,right.ParentProcessId),ProcFieldKind.ProcessGroup=>CompareObserved(left.ProcessGroupId,right.ProcessGroupId),ProcFieldKind.Session=>CompareObserved(left.SessionId,right.SessionId),ProcFieldKind.EffectiveUser=>CompareObserved(left.EffectiveUserId,right.EffectiveUserId),ProcFieldKind.Nice=>CompareObserved(left.NiceValue,right.NiceValue),ProcFieldKind.Threads=>CompareObserved(left.ThreadCount,right.ThreadCount),ProcFieldKind.ResidentMemory=>CompareObserved(left.ResidentMemoryBytes,right.ResidentMemoryBytes),ProcFieldKind.VirtualMemory=>CompareObserved(left.VirtualMemoryBytes,right.VirtualMemoryBytes),_=>StringComparer.Ordinal.Compare(ProcFieldCatalog.Format(left,field),ProcFieldCatalog.Format(right,field))}; private static int CompareObserved<T>(ProcObservedValue<T> left,ProcObservedValue<T> right)where T:IComparable<T>{if(left.HasValue&&right.HasValue)return left.Value.CompareTo(right.Value);if(left.HasValue)return -1;return right.HasValue?1:0;} }
public sealed class ProcDisplayConfiguration { public IReadOnlyList<ProcFieldDefinition> Fields{get;} public IReadOnlyList<ProcSortKey> SortKeys{get;} public ProcPersonality Personality{get;} public int? Width{get;} public ProcDisplayConfiguration(IEnumerable<ProcFieldDefinition> fields,IEnumerable<ProcSortKey>? sortKeys=null,ProcPersonality personality=ProcPersonality.Linux,int? width=null){ArgumentNullException.ThrowIfNull(fields);if(width is <=0)throw new ArgumentOutOfRangeException(nameof(width));this.Fields=fields.ToArray();this.SortKeys=null==sortKeys?Array.Empty<ProcSortKey>():sortKeys.ToArray();this.Personality=personality;this.Width=width;} }
public sealed class ProcScreenRow { public int ProcessId{get;} public IReadOnlyList<string> Cells{get;} public ProcScreenRow(int processId,IEnumerable<string> cells){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(processId);ArgumentNullException.ThrowIfNull(cells);this.ProcessId=processId;this.Cells=cells.ToArray();} }
public sealed class ProcScreenFrame { public long Sequence{get;} public TimeSpan Elapsed{get;} public IReadOnlyList<string> Headers{get;} public IReadOnlyList<ProcScreenRow> Rows{get;} public ProcScreenFrame(long sequence,TimeSpan elapsed,IEnumerable<string> headers,IEnumerable<ProcScreenRow> rows){ArgumentOutOfRangeException.ThrowIfNegative(sequence);if(TimeSpan.Zero>elapsed)throw new ArgumentOutOfRangeException(nameof(elapsed));ArgumentNullException.ThrowIfNull(headers);ArgumentNullException.ThrowIfNull(rows);this.Sequence=sequence;this.Elapsed=elapsed;this.Headers=headers.ToArray();this.Rows=rows.ToArray();} }
public static class ProcScreenBuilder { public static ProcScreenFrame Build(long sequence,TimeSpan elapsed,IEnumerable<ProcProcessSnapshot> processes,ProcDisplayConfiguration configuration){ArgumentNullException.ThrowIfNull(processes);ArgumentNullException.ThrowIfNull(configuration);var sorted=ProcProcessSorter.Sort(processes,configuration.SortKeys);var rows=sorted.Select(process=>new ProcScreenRow(process.ProcessId,configuration.Fields.Select(field=>ProcFieldCatalog.Format(process,field.Kind))));return new ProcScreenFrame(sequence,elapsed,configuration.Fields.Select(field=>field.Header),rows);} }
