namespace Icod.ProcPs.Shared;

using System.Globalization;
using System.Runtime.InteropServices;
using Icod.CommandFramework.Host;

public sealed class ProcCpuTimes {
	public ulong User { get; }
	public ulong Nice { get; }
	public ulong System { get; }
	public ulong Idle { get; }
	public ulong IoWait { get; }
	public ulong Irq { get; }
	public ulong SoftIrq { get; }
	public ulong Steal { get; }
	public ulong Guest { get; }
	public ulong GuestNice { get; }
	public ulong Total => unchecked( this.User + this.Nice + this.System + this.Idle + this.IoWait + this.Irq + this.SoftIrq + this.Steal );
	public ProcCpuTimes( ulong user, ulong nice, ulong system, ulong idle, ulong ioWait, ulong irq, ulong softIrq, ulong steal, ulong guest, ulong guestNice ) {
		this.User = user; this.Nice = nice; this.System = system; this.Idle = idle; this.IoWait = ioWait; this.Irq = irq; this.SoftIrq = softIrq; this.Steal = steal; this.Guest = guest; this.GuestNice = guestNice;
	}
}
public sealed class ProcCpuActivity {
	public ulong User { get; }
	public ulong System { get; }
	public ulong Idle { get; }
	public ulong? Nice { get; }
	public ulong? Wait { get; }
	public ulong? Other { get; }
	public int CounterBitWidth { get; }
	public ulong Total => unchecked( this.User + this.System + this.Idle + ( this.Nice ?? 0UL ) + ( this.Wait ?? 0UL ) + ( this.Other ?? 0UL ) );
	public ProcCpuActivity( ulong user, ulong system, ulong idle, ulong? nice = null, ulong? wait = null, ulong? other = null, int counterBitWidth = 64 ) { if ( 1 > counterBitWidth || 64 < counterBitWidth ) throw new ArgumentOutOfRangeException( nameof( counterBitWidth ) ); this.User=user; this.System=system; this.Idle=idle; this.Nice=nice; this.Wait=wait; this.Other=other; this.CounterBitWidth=counterBitWidth; }
}
public sealed class ProcLoadAverages { public double OneMinute{get;} public double FiveMinutes{get;} public double FifteenMinutes{get;} public ProcLoadAverages(double oneMinute,double fiveMinutes,double fifteenMinutes){this.OneMinute=oneMinute;this.FiveMinutes=fiveMinutes;this.FifteenMinutes=fifteenMinutes;} }
public sealed class ProcLoadAverage { public double OneMinute{get;} public double FiveMinutes{get;} public double FifteenMinutes{get;} public int Runnable{get;} public int TotalEntities{get;} public int LastProcessId{get;} public ProcLoadAverage(double oneMinute,double fiveMinutes,double fifteenMinutes,int runnable,int totalEntities,int lastProcessId){this.OneMinute=oneMinute;this.FiveMinutes=fiveMinutes;this.FifteenMinutes=fifteenMinutes;this.Runnable=runnable;this.TotalEntities=totalEntities;this.LastProcessId=lastProcessId;} }
public sealed class ProcUptimeInfo { public TimeSpan Uptime{get;} public TimeSpan? IdleTime{get;} public ProcUptimeInfo(TimeSpan uptime,TimeSpan? idleTime){if(TimeSpan.Zero>uptime)throw new ArgumentOutOfRangeException(nameof(uptime));this.Uptime=uptime;this.IdleTime=idleTime;} }
public sealed class ProcMemoryInfo {
	public IReadOnlyDictionary<string,ulong> Fields{get;} public ulong? TotalBytes{get;} public ulong? FreeBytes{get;} public ulong? AvailableBytes{get;} public ulong? BuffersBytes{get;} public ulong? CacheBytes{get;} public ulong? SharedBytes{get;} public ulong? SwapTotalBytes{get;} public ulong? SwapFreeBytes{get;} public ulong? CommitLimitBytes{get;} public ulong? CommittedBytes{get;} public ulong? LowTotalBytes{get;} public ulong? LowFreeBytes{get;} public ulong? HighTotalBytes{get;} public ulong? HighFreeBytes{get;}
	public ProcMemoryInfo(IReadOnlyDictionary<string,ulong> fields){ArgumentNullException.ThrowIfNull(fields);this.Fields=fields;this.TotalBytes=Get(fields,"MemTotal");this.FreeBytes=Get(fields,"MemFree");this.AvailableBytes=Get(fields,"MemAvailable");this.BuffersBytes=Get(fields,"Buffers");this.CacheBytes=SaturatingAdd(Get(fields,"Cached"),Get(fields,"SReclaimable"));this.SharedBytes=Get(fields,"Shmem");this.SwapTotalBytes=Get(fields,"SwapTotal");this.SwapFreeBytes=Get(fields,"SwapFree");this.CommitLimitBytes=Get(fields,"CommitLimit");this.CommittedBytes=Get(fields,"Committed_AS");this.LowTotalBytes=Get(fields,"LowTotal");this.LowFreeBytes=Get(fields,"LowFree");this.HighTotalBytes=Get(fields,"HighTotal");this.HighFreeBytes=Get(fields,"HighFree");}
	public ProcMemoryInfo(ulong? totalBytes,ulong? freeBytes,ulong? availableBytes,ulong? buffersBytes=null,ulong? cacheBytes=null,ulong? sharedBytes=null,ulong? swapTotalBytes=null,ulong? swapFreeBytes=null,ulong? commitLimitBytes=null,ulong? committedBytes=null,ulong? lowTotalBytes=null,ulong? lowFreeBytes=null,ulong? highTotalBytes=null,ulong? highFreeBytes=null,IReadOnlyDictionary<string,ulong>? fields=null){this.Fields=fields??new Dictionary<string,ulong>(StringComparer.Ordinal);this.TotalBytes=totalBytes;this.FreeBytes=freeBytes;this.AvailableBytes=availableBytes;this.BuffersBytes=buffersBytes;this.CacheBytes=cacheBytes;this.SharedBytes=sharedBytes;this.SwapTotalBytes=swapTotalBytes;this.SwapFreeBytes=swapFreeBytes;this.CommitLimitBytes=commitLimitBytes;this.CommittedBytes=committedBytes;this.LowTotalBytes=lowTotalBytes;this.LowFreeBytes=lowFreeBytes;this.HighTotalBytes=highTotalBytes;this.HighFreeBytes=highFreeBytes;}
	private static ulong? Get(IReadOnlyDictionary<string,ulong> fields,string key)=>fields.TryGetValue(key,out var value)?value:null; private static ulong? SaturatingAdd(ulong? left,ulong? right){if(!left.HasValue&&!right.HasValue)return null;var l=left??0UL;var r=right??0UL;return ulong.MaxValue-l<r?ulong.MaxValue:l+r;}
}
public sealed class ProcSlabEntry { public string Name{get;} public ulong ActiveObjects{get;} public ulong TotalObjects{get;} public ulong ObjectSizeBytes{get;} public ulong ObjectsPerSlab{get;} public ulong PagesPerSlab{get;} public ProcSlabEntry(string name,ulong activeObjects,ulong totalObjects,ulong objectSizeBytes,ulong objectsPerSlab,ulong pagesPerSlab){ArgumentException.ThrowIfNullOrWhiteSpace(name);this.Name=name;this.ActiveObjects=activeObjects;this.TotalObjects=totalObjects;this.ObjectSizeBytes=objectSizeBytes;this.ObjectsPerSlab=objectsPerSlab;this.PagesPerSlab=pagesPerSlab;} }
public sealed class ProcHugePageInfo { public ulong TotalPages{get;} public ulong FreePages{get;} public ulong ReservedPages{get;} public ulong SurplusPages{get;} public ulong PageSizeBytes{get;} public ProcHugePageInfo(ulong totalPages,ulong freePages,ulong reservedPages,ulong surplusPages,ulong pageSizeBytes){this.TotalPages=totalPages;this.FreePages=freePages;this.ReservedPages=reservedPages;this.SurplusPages=surplusPages;this.PageSizeBytes=pageSizeBytes;} }
public sealed class ProcUserSessionInfo { public int Count{get;} public ProcUserSessionInfo(int count){ArgumentOutOfRangeException.ThrowIfNegative(count);this.Count=count;} }
public sealed class ProcSystemSnapshot { public ProcObservedValue<ProcCpuTimes> Cpu{get;init;}=ProcObservedValue<ProcCpuTimes>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<ProcCpuActivity> CpuActivity{get;init;}=ProcObservedValue<ProcCpuActivity>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<ProcMemoryInfo> Memory{get;init;}=ProcObservedValue<ProcMemoryInfo>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<ProcLoadAverage> LoadAverage{get;init;}=ProcObservedValue<ProcLoadAverage>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<ProcLoadAverages> LoadAverages{get;init;}=ProcObservedValue<ProcLoadAverages>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<ProcUptimeInfo> Uptime{get;init;}=ProcObservedValue<ProcUptimeInfo>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<IReadOnlyDictionary<string,ulong>> VirtualMemory{get;init;}=ProcObservedValue<IReadOnlyDictionary<string,ulong>>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<IReadOnlyList<ProcSlabEntry>> Slab{get;init;}=ProcObservedValue<IReadOnlyList<ProcSlabEntry>>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<ProcHugePageInfo> HugePages{get;init;}=ProcObservedValue<ProcHugePageInfo>.Missing(ProcObservationAvailability.Unavailable); public ProcObservedValue<ProcUserSessionInfo> UserSessions{get;init;}=ProcObservedValue<ProcUserSessionInfo>.Missing(ProcObservationAvailability.Unavailable); }
public interface IProcSystemMetricsProvider { ProcSystemCapabilities Capabilities{get;} Task<ProcSystemSnapshot> GetSnapshotAsync(CancellationToken cancellationToken=default); async Task<ProcObservedValue<ProcMemoryInfo>> GetMemoryAsync(CancellationToken cancellationToken=default)=>(await this.GetSnapshotAsync(cancellationToken).ConfigureAwait(false)).Memory; async Task<ProcObservedValue<ProcUptimeInfo>> GetUptimeAsync(bool containerMode,CancellationToken cancellationToken=default){if(containerMode)return ProcObservedValue<ProcUptimeInfo>.Missing(ProcObservationAvailability.Unsupported,"Container uptime is not exposed by this provider.");return(await this.GetSnapshotAsync(cancellationToken).ConfigureAwait(false)).Uptime;} }
public sealed class SystemProcSystemMetricsProvider:IProcSystemMetricsProvider { private readonly IProcSystemMetricsProvider _inner; public static SystemProcSystemMetricsProvider Instance{get;}=new(); public ProcSystemCapabilities Capabilities=>this._inner.Capabilities; public SystemProcSystemMetricsProvider(){this._inner=OperatingSystem.IsLinux()?new LinuxProcSystemMetricsProvider():OperatingSystem.IsWindows()?new WindowsProcSystemMetricsProvider():OperatingSystem.IsMacOS()?new MacOsProcSystemMetricsProvider():new PortableProcSystemMetricsProvider();} public Task<ProcSystemSnapshot> GetSnapshotAsync(CancellationToken cancellationToken=default)=>this._inner.GetSnapshotAsync(cancellationToken); public Task<ProcObservedValue<ProcMemoryInfo>> GetMemoryAsync(CancellationToken cancellationToken=default)=>this._inner.GetMemoryAsync(cancellationToken); public Task<ProcObservedValue<ProcUptimeInfo>> GetUptimeAsync(bool containerMode,CancellationToken cancellationToken=default)=>this._inner.GetUptimeAsync(containerMode,cancellationToken); }
public sealed class LinuxProcSystemMetricsProvider:IProcSystemMetricsProvider {
	private const short UserProcessRecord=7; private static readonly object UserSessionSync=new(); private readonly string _procRoot; public ProcSystemCapabilities Capabilities=>ProcSystemCapabilities.Memory|ProcSystemCapabilities.Swap|ProcSystemCapabilities.CpuActivity|ProcSystemCapabilities.LoadAverage|ProcSystemCapabilities.Uptime|ProcSystemCapabilities.VirtualMemory|ProcSystemCapabilities.Slab|ProcSystemCapabilities.HugePages|ProcSystemCapabilities.UserSessions; public LinuxProcSystemMetricsProvider(string procRoot="/proc"){ArgumentException.ThrowIfNullOrWhiteSpace(procRoot);this._procRoot=procRoot;}
	public Task<ProcObservedValue<ProcMemoryInfo>> GetMemoryAsync(CancellationToken cancellationToken=default)=>ObserveFileAsync("meminfo",text=>new ProcMemoryInfo(LinuxProcParsers.ParseMemInfo(text)),cancellationToken);
	public async Task<ProcObservedValue<ProcUptimeInfo>> GetUptimeAsync(bool containerMode,CancellationToken cancellationToken=default){if(!containerMode)return await ObserveFileAsync("uptime",ParseUptime,cancellationToken).ConfigureAwait(false);if(!OperatingSystem.IsLinux())return ProcObservedValue<ProcUptimeInfo>.Missing(ProcObservationAvailability.Unsupported,"Container uptime with procps-ng semantics is available only on Linux.");var system=await ObserveFileAsync("uptime",ParseUptime,cancellationToken).ConfigureAwait(false);if(!system.HasValue)return system;var init=await ObserveFileAsync(System.IO.Path.Combine("1","stat"),LinuxProcParsers.ParseProcessStat,cancellationToken).ConfigureAwait(false);if(!init.HasValue)return ProcObservedValue<ProcUptimeInfo>.Missing(init.Availability,init.Diagnostic);try{var ticks=LinuxSystemNative.SysConf(LinuxSystemNative.ClockTicksPerSecond);if(0>=ticks)return ProcObservedValue<ProcUptimeInfo>.Missing(ProcObservationAvailability.Unavailable,"sysconf(_SC_CLK_TCK) did not return a positive clock frequency.");var start=init.Value.StartTimeTicks/(double)ticks;return ProcObservedValue<ProcUptimeInfo>.Available(new ProcUptimeInfo(TimeSpan.FromSeconds(Math.Max(0d,system.Value.Uptime.TotalSeconds-start)),null),ProcObservationSource.Derived,ObservationFidelity.Exact);}catch(DllNotFoundException ex){return ProcObservedValue<ProcUptimeInfo>.Missing(ProcObservationAvailability.Unsupported,ex.Message);}catch(EntryPointNotFoundException ex){return ProcObservedValue<ProcUptimeInfo>.Missing(ProcObservationAvailability.Unsupported,ex.Message);}}
	public async Task<ProcSystemSnapshot> GetSnapshotAsync(CancellationToken cancellationToken=default){var stat=await ObserveFileAsync("stat",ParseCpu,cancellationToken).ConfigureAwait(false);var memory=await ObserveFileAsync("meminfo",text=>new ProcMemoryInfo(LinuxProcParsers.ParseMemInfo(text)),cancellationToken).ConfigureAwait(false);var load=await ObserveFileAsync("loadavg",ParseLoadAverage,cancellationToken).ConfigureAwait(false);var uptime=await ObserveFileAsync("uptime",ParseUptime,cancellationToken).ConfigureAwait(false);var vm=await ObserveFileAsync<IReadOnlyDictionary<string,ulong>>("vmstat",LinuxProcParsers.ParseCounterFile,cancellationToken).ConfigureAwait(false);var slab=await ObserveFileAsync<IReadOnlyList<ProcSlabEntry>>("slabinfo",ParseSlabInfo,cancellationToken).ConfigureAwait(false);var huge=memory.HasValue?ParseHugePages(memory.Value):ProcObservedValue<ProcHugePageInfo>.Missing(memory.Availability,memory.Diagnostic);var users=ObserveUserSessions();var neutralCpu=stat.HasValue?ProcObservedValue<ProcCpuActivity>.Available(new ProcCpuActivity(stat.Value.User,SaturatingAdd(stat.Value.System,SaturatingAdd(stat.Value.Irq,stat.Value.SoftIrq)),stat.Value.Idle,stat.Value.Nice,stat.Value.IoWait,stat.Value.Steal),ProcObservationSource.LinuxProcfs,ObservationFidelity.Exact):ProcObservedValue<ProcCpuActivity>.Missing(stat.Availability,stat.Diagnostic);var neutralLoad=load.HasValue?ProcObservedValue<ProcLoadAverages>.Available(new ProcLoadAverages(load.Value.OneMinute,load.Value.FiveMinutes,load.Value.FifteenMinutes),ProcObservationSource.LinuxProcfs,ObservationFidelity.Exact):ProcObservedValue<ProcLoadAverages>.Missing(load.Availability,load.Diagnostic);return new ProcSystemSnapshot{Cpu=stat,CpuActivity=neutralCpu,Memory=memory,LoadAverage=load,LoadAverages=neutralLoad,Uptime=uptime,VirtualMemory=vm,Slab=slab,HugePages=huge,UserSessions=users};}
	private static ProcObservedValue<ProcUserSessionInfo> ObserveUserSessions(){if(!OperatingSystem.IsLinux())return ProcObservedValue<ProcUserSessionInfo>.Missing(ProcObservationAvailability.Unsupported,"The Linux user-session provider is available only on Linux.");lock(UserSessionSync){var opened=false;try{LinuxSessionNative.SetUtmpxEnt();opened=true;var count=0;while(true){var entry=LinuxSessionNative.GetUtmpxEnt();if(IntPtr.Zero==entry)break;if(UserProcessRecord==Marshal.ReadInt16(entry))count++;}return ProcObservedValue<ProcUserSessionInfo>.Available(new ProcUserSessionInfo(count),ProcObservationSource.PosixLibc,ObservationFidelity.Equivalent);}catch(DllNotFoundException ex){return ProcObservedValue<ProcUserSessionInfo>.Missing(ProcObservationAvailability.Unsupported,ex.Message);}catch(EntryPointNotFoundException ex){return ProcObservedValue<ProcUserSessionInfo>.Missing(ProcObservationAvailability.Unsupported,ex.Message);}finally{if(opened){try{LinuxSessionNative.EndUtmpxEnt();}catch(DllNotFoundException){}catch(EntryPointNotFoundException){}}}}}
	private static class LinuxSystemNative{public const int ClockTicksPerSecond=2;[DllImport("libc",EntryPoint="sysconf",ExactSpelling=true,SetLastError=true)]public static extern long SysConf(int name);} private static class LinuxSessionNative{[DllImport("libc",EntryPoint="setutxent",ExactSpelling=true)]internal static extern void SetUtmpxEnt();[DllImport("libc",EntryPoint="getutxent",ExactSpelling=true)]internal static extern IntPtr GetUtmpxEnt();[DllImport("libc",EntryPoint="endutxent",ExactSpelling=true)]internal static extern void EndUtmpxEnt();}
	private async Task<ProcObservedValue<T>> ObserveFileAsync<T>(string fileName,Func<string,T> parser,CancellationToken cancellationToken){try{var text=await File.ReadAllTextAsync(System.IO.Path.Combine(this._procRoot,fileName),cancellationToken).ConfigureAwait(false);return ProcObservedValue<T>.Available(parser(text),ProcObservationSource.LinuxProcfs,ObservationFidelity.Exact);}catch(UnauthorizedAccessException ex){return ProcObservedValue<T>.Missing(ProcObservationAvailability.AccessDenied,ex.Message);}catch(FileNotFoundException ex){return ProcObservedValue<T>.Missing(ProcObservationAvailability.Unavailable,ex.Message);}catch(DirectoryNotFoundException ex){return ProcObservedValue<T>.Missing(ProcObservationAvailability.Unavailable,ex.Message);}catch(IOException ex){return ProcObservedValue<T>.Missing(ProcObservationAvailability.Unavailable,ex.Message);}catch(FormatException ex){return ProcObservedValue<T>.Missing(ProcObservationAvailability.Malformed,ex.Message);}catch(OverflowException ex){return ProcObservedValue<T>.Missing(ProcObservationAvailability.Malformed,ex.Message);}}
	public static ProcCpuTimes ParseCpu(string text){var line=text.Split('\n').FirstOrDefault(value=>value.StartsWith("cpu ",StringComparison.Ordinal))??throw new FormatException("The aggregate cpu line is missing.");var fields=line.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries);if(5>fields.Length)throw new FormatException("The aggregate cpu line is incomplete.");ulong Read(int index)=>index<fields.Length?ulong.Parse(fields[index],NumberStyles.None,CultureInfo.InvariantCulture):0UL;return new ProcCpuTimes(Read(1),Read(2),Read(3),Read(4),Read(5),Read(6),Read(7),Read(8),Read(9),Read(10));}
	public static ProcLoadAverage ParseLoadAverage(string text){var fields=text.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries);if(5>fields.Length)throw new FormatException("Malformed /proc/loadavg.");var entities=fields[3].Split('/',2);if(2!=entities.Length)throw new FormatException("Malformed loadavg runnable/total field.");return new ProcLoadAverage(double.Parse(fields[0],NumberStyles.Float,CultureInfo.InvariantCulture),double.Parse(fields[1],NumberStyles.Float,CultureInfo.InvariantCulture),double.Parse(fields[2],NumberStyles.Float,CultureInfo.InvariantCulture),int.Parse(entities[0],NumberStyles.None,CultureInfo.InvariantCulture),int.Parse(entities[1],NumberStyles.None,CultureInfo.InvariantCulture),int.Parse(fields[4],NumberStyles.None,CultureInfo.InvariantCulture));}
	public static ProcUptimeInfo ParseUptime(string text){var fields=text.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries);if(1>fields.Length)throw new FormatException("Malformed /proc/uptime.");var uptime=TimeSpan.FromSeconds(double.Parse(fields[0],NumberStyles.Float,CultureInfo.InvariantCulture));TimeSpan? idle=1<fields.Length?TimeSpan.FromSeconds(double.Parse(fields[1],NumberStyles.Float,CultureInfo.InvariantCulture)):null;return new ProcUptimeInfo(uptime,idle);}
	public static IReadOnlyList<ProcSlabEntry> ParseSlabInfo(string text){var entries=new List<ProcSlabEntry>();foreach(var line in text.Split('\n',StringSplitOptions.RemoveEmptyEntries)){if(line.StartsWith("slabinfo",StringComparison.Ordinal)||line.StartsWith("#",StringComparison.Ordinal))continue;var fields=line.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries);if(6>fields.Length)continue;if(!ulong.TryParse(fields[1],NumberStyles.None,CultureInfo.InvariantCulture,out var active))continue;if(!ulong.TryParse(fields[2],NumberStyles.None,CultureInfo.InvariantCulture,out var total))continue;if(!ulong.TryParse(fields[3],NumberStyles.None,CultureInfo.InvariantCulture,out var size))continue;if(!ulong.TryParse(fields[4],NumberStyles.None,CultureInfo.InvariantCulture,out var perSlab))continue;if(!ulong.TryParse(fields[5],NumberStyles.None,CultureInfo.InvariantCulture,out var pages))continue;entries.Add(new ProcSlabEntry(fields[0],active,total,size,perSlab,pages));}return entries;}
	private static ProcObservedValue<ProcHugePageInfo> ParseHugePages(ProcMemoryInfo memory){ulong Read(string key)=>memory.Fields.TryGetValue(key,out var value)?value:0UL;return ProcObservedValue<ProcHugePageInfo>.Available(new ProcHugePageInfo(Read("HugePages_Total"),Read("HugePages_Free"),Read("HugePages_Rsvd"),Read("HugePages_Surp"),Read("Hugepagesize")),ProcObservationSource.LinuxProcfs,ObservationFidelity.Exact);} private static ulong SaturatingAdd(ulong left,ulong right)=>ulong.MaxValue-left<right?ulong.MaxValue:left+right;
}
public sealed class PortableProcSystemMetricsProvider:IProcSystemMetricsProvider { public ProcSystemCapabilities Capabilities=>ProcSystemCapabilities.Uptime; public async Task<ProcObservedValue<ProcMemoryInfo>> GetMemoryAsync(CancellationToken cancellationToken=default)=>(await this.GetSnapshotAsync(cancellationToken).ConfigureAwait(false)).Memory; public async Task<ProcObservedValue<ProcUptimeInfo>> GetUptimeAsync(bool containerMode,CancellationToken cancellationToken=default){cancellationToken.ThrowIfCancellationRequested();if(containerMode)return ProcObservedValue<ProcUptimeInfo>.Missing(ProcObservationAvailability.Unsupported,"Container uptime with procps-ng semantics is not exposed by the portable provider.");return(await this.GetSnapshotAsync(cancellationToken).ConfigureAwait(false)).Uptime;} public Task<ProcSystemSnapshot> GetSnapshotAsync(CancellationToken cancellationToken=default){cancellationToken.ThrowIfCancellationRequested();var unsupported="Linux procps-ng system metric semantics are not exposed by the portable provider.";return Task.FromResult(new ProcSystemSnapshot{Cpu=ProcObservedValue<ProcCpuTimes>.Missing(ProcObservationAvailability.Unsupported,unsupported),CpuActivity=ProcObservedValue<ProcCpuActivity>.Missing(ProcObservationAvailability.Unsupported,unsupported),Memory=ProcObservedValue<ProcMemoryInfo>.Missing(ProcObservationAvailability.Unsupported,unsupported),LoadAverage=ProcObservedValue<ProcLoadAverage>.Missing(ProcObservationAvailability.Unsupported,unsupported),LoadAverages=ProcObservedValue<ProcLoadAverages>.Missing(ProcObservationAvailability.Unsupported,unsupported),Uptime=ProcObservedValue<ProcUptimeInfo>.Available(new ProcUptimeInfo(TimeSpan.FromMilliseconds(Environment.TickCount64),null),ProcObservationSource.PlatformApi,ObservationFidelity.Equivalent),VirtualMemory=ProcObservedValue<IReadOnlyDictionary<string,ulong>>.Missing(ProcObservationAvailability.Unsupported,unsupported),Slab=ProcObservedValue<IReadOnlyList<ProcSlabEntry>>.Missing(ProcObservationAvailability.Unsupported,unsupported),HugePages=ProcObservedValue<ProcHugePageInfo>.Missing(ProcObservationAvailability.Unsupported,unsupported),UserSessions=ProcObservedValue<ProcUserSessionInfo>.Missing(ProcObservationAvailability.Unsupported,unsupported)});} }
