name: pr-build

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - run: dotnet clean Icod.ProcPs.sln -c Debug
      - run: dotnet restore Icod.ProcPs.sln
      - run: dotnet build Icod.ProcPs.sln -c Debug --no-restore
